### ISSUE TITLE
No paytype(s)! Missing test parameter?

### ISSUE THREAD

**Issue by LarsJonsson** [DIBS-Payment-Services/magento2-dibs-flexwin#1]
I'm testing the current DIBS Flexwin module version for Magento 2. 
When trying to make a payment, I get an error message in the Payment window: "No paytype(s)! Missing test parameter?".

Here's my settings in Magento Admin for Dibs Flexwin:

Merchant Country: Sweden
MerchantID: xxx
Language: Sweden
Testmode: Yes
Capturenow: No
Decorator: Default
md5 Key1: yyy
md5 Key2: zzz
Enabled: Yes

Everything looks fine until I get to the paymnet Windows.

Best regards,
Lars Jonsson
Netrix AB

**Comment by maxwhite** [comment]
Hi, could you write to me email to
mabe@dibs.dk and provide your merchantid ?

**Comment by LarsJonsson** [comment]
Hi,
My Merchant ID is 90197236

Best regards,
Lars Jonsson
Netrix AB

Från: maxwhite [mailto:notifications@github.com]
Skickat: den 13 april 2016 16:05
Till: DIBS-Payment-Services/magento2-dibs-flexwin <magento2-dibs-flexwin@noreply.github.com>
Kopia: Lars Jonsson <lj@netrixab.se>
Ämne: Re: [DIBS-Payment-Services/magento2-dibs-flexwin] No paytype(s)! Missing test parameter? (#1)


Hi, could you write to me email to
mabe@dibs.dk<mailto:mabe@dibs.dk> and provide your merchantid ?

**Comment by maxwhite** [comment]
I've checked your account, ant current status of your account is closed. You should contact our support and ask them to set up your account settings

**Comment by LarsJonsson** [comment]
I called DIBS, and the account's test transacations was disabled. It is now enabled, and  I can now make test transactions.
Thanks for your help!
