### ISSUE TITLE
Card selector confusing to end-users

### ISSUE THREAD

**Issue by peec** [DIBS-Payment-Services/magento2-dibs-flexwin#10]
The card selector is quite confusing where to click ( one can't know that its a button ) Maybe a button or checkbox is more convenient to chose a specific payment method.

Here is a screenshot what i mean:

![image](https://cloud.githubusercontent.com/assets/131546/16264909/a50e7364-387c-11e6-81c6-39f36268b091.png)

**Comment by maxwhite** [comment]
Why on your screenshot there are no radiobuttons ?
![checkout_radiobutton](https://cloud.githubusercontent.com/assets/1072153/16270896/962aac04-38a0-11e6-80ad-06fbe0cd4b4f.png)

**Comment by peec** [comment]
It seems that these have "display: none" on the radio button somehow,

When I remove "display: none" in console, they appear. This is strange.

I only have DIBS payment methods enabled right now ( not any others, might this be the case ) ? 

Currently used latest of "dibs/module-payment-flexwin": "^1.1"

![image](https://cloud.githubusercontent.com/assets/131546/16295046/9b2dc23e-3924-11e6-9f3e-ce7642a8c525.png)

**Comment by maxwhite** [comment]
Please provide your environment OS, browser version

**Comment by peec** [comment]
I figured that once i enabled another payment method (e.g. Money check order ) , the radios appears. So there are probably some configuration to enable this radio button somewhere.

To reproduce, disable all payment methods except Dibs.


PHP 7
Chrome latest
2.1.0-RC-3 and 2.0.7 of mangeto.
