### ISSUE TITLE
NOT working in Magento 2.1.3

### ISSUE THREAD

**Issue by xnhinzkyx** [DIBS-Payment-Services/magento2-dibs-flexwin#15]
I can't find it in the backend after installation.

Running these commands:

`composer require dibs/module-payment-flexwin`

`php bin/magento module:enable Dibs_Flexwin`

Any fixes for this?

**Comment by petterkj** [comment]
2.1.3 issue , but might be fixed within this module?

See.

https://github.com/magento/magento2/issues/7891#issuecomment-268203393

**Comment by maxwhite** [comment]
HI, thanks for report we will investigate it

**Comment by xnhinzkyx** [comment]
I managed to fixed it.

To show it in the backend, I edited this file:

`vendor/dibs/module-payment-flexwin/etc/adminhtml/system.xml`

And on line 5 I changed "**sortOrder**" value from **2** to **200** or I think you can change it to a number that won't conflict with other payment module.

From:

`<group id="dibs_flexwin_all" translate="label" type="text" sortOrder="2" showInDefault="1" showInWebsite="1" showInStore="1">`

To:

**<group id="dibs_flexwin_all" translate="label" type="text" sortOrder="200" showInDefault="1" showInWebsite="1" showInStore="1">**

And in my case, I am using porto theme so I replaced all the files inside porto theme (I am using porto child as my default theme). Clear or Flush the cache, remove files inside static files and deploy it again.

I run this command:

$ rm -rf var/composer_home/* var/generation/* var/page_cache/* var/view_preprocessed/*
$ rm -rf pub/static/*
$ php bin/magento -vvv setup:static-content:deploy

Now it works for me.
