### ISSUE TITLE
order confirmation email is not sent

### ISSUE THREAD

**Issue by abad93** [DIBS-Payment-Services/magento2-dibs-flexwin#17]
I didn't recieve order confirmation email after successfully order using DIBS payment Test Account. It works on paypal test account. Any idea how to fix this?  

In my Backend order information, I got this message "Order # 000000027 (The order confirmation email is not sent)".

Magento 2.1.3
PHP 7

**Comment by maxwhite** [comment]
HI, 
check this article http://tech.dibspayment.com/shopmodules/magento2
How to configure DIBS Payment system for the module (D2)

Also in DIBS Admin check setting:
Integration->FlexWin->FlexWin settings->Skip accept page 
It should be unchecked

**Comment by abad93** [comment]
Thanks. It's now working.
