### ISSUE TITLE
Order cancel via admin panel does not cancel automatically in DIBS

### ISSUE THREAD

**Issue by unicoder88** [DIBS-Payment-Services/magento2-dibs-flexwin#19]
Good day,

Order cancellation by admin does not update DIBS order and it has to be updated manually.
Please add a cancel command in addition to capture and refund.

Thanks!

**Comment by maxwhite** [comment]
HI, thanks for feedback we will add it asap

**Comment by unicoder88** [comment]
Any update on this?

**Comment by unicoder88** [comment]
Any promises?

**Comment by maxwhite** [comment]
HI, it will be ready in 3 weeks

**Comment by vmalyk** [comment]
HI! Any updates about progress for this issue?
