### ISSUE TITLE
Ability to select Order Status for differet payment states

### ISSUE THREAD

**Issue by LarsJonsson** [DIBS-Payment-Services/magento2-dibs-flexwin#2]
We would like there to be an option to select New Order status (see attachment), and also an option to select status for other payment states, so that we can select from our own custom order statuses created under Stores > Order Status. 
![neworderstatus](https://cloud.githubusercontent.com/assets/15812729/14494747/c46c2a8e-018c-11e6-8eab-c89585a7ec55.jpg)

**Comment by maxwhite** [comment]
Thanks for your feedback, it will be added with the next release in 2 days

**Comment by maxwhite** [comment]
New version with this changes available: 
https://github.com/DIBS-Payment-Services/magento2-dibs-flexwin/releases/tag/1.1.0

**Comment by LarsJonsson** [comment]
It's now possible to select our own Order Status After Paymnet. However, after completing a paymnet, the order status is still Pending Payment.
Settings:
![dibs-magento2](https://cloud.githubusercontent.com/assets/15812729/14776813/23c4c44c-0ac9-11e6-853d-90b6ca361fe9.jpg)

**Comment by LarsJonsson** [comment]
Also, there is no DIBS transaction number on the orders after puchase (but there was in the first version).

**Comment by LarsJonsson** [comment]
Hi Maxim,
We are going to release a new webshop now on Monday 2 may.  We would therefore appreciate if you could check out the problem with the missing transaction numbers in the Magento order after a payment.
See  https://github.com/DIBS-Payment-Services/magento2-dibs-flexwin/issues/2.

Best regards,
Lars Jonsson
Netrix AB



Från: maxwhite [mailto:notifications@github.com]
Skickat: den 15 april 2016 20:08
Till: DIBS-Payment-Services/magento2-dibs-flexwin <magento2-dibs-flexwin@noreply.github.com>
Kopia: Lars Jonsson <lj@netrixab.se>
Ämne: Re: [DIBS-Payment-Services/magento2-dibs-flexwin] Ability to select Order Status for differet payment states (#2)


Thanks for your feedback, it will be added with the next release in 2 days
