### ISSUE TITLE
Callbacks doesn't seem to work?

### ISSUE THREAD

**Issue by petterkj** [DIBS-Payment-Services/magento2-dibs-flexwin#20]
Hello,

We have a customer running live on v. 2.X of this plugin.

However the statuses doesn't seem to change on  the order, e.g. "Payment pending" and Processing doesn't get assigned when a customer has gone throguht a successful credit card.

We have stock order statuses, we just configured them in the settings.

**Comment by maxwhite** [comment]
Hi, 
please check documentation: 
http://tech.dibspayment.com/shopmodules/magento2
How to configure DIBS Payment system for the module (D2)
