### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isEnabled' of undefined

### ISSUE THREAD

**Issue by xnhinzkyx** [DIBS-Payment-Services/magento2-dibs-flexwin#22]
This error appears in console and i can't proceed checkout process choosing Dibs Visa or Mastercard as payment.

I have opened the file set-payment-method.js and found this lines:

```
// some copy-paste from place-order-mixin.js for adding agreements...
            if (agreementsConfig.isEnabled) {
                    var agreementForm = $('.payment-method._active form[data-role=checkout-agreements]'),
                agreementData = agreementForm.serializeArray(),
                agreementIds = [];
                agreementData.forEach(function(item) {
                    agreementIds.push(item.value);
                });
                paymentData.extension_attributes = {agreement_ids: agreementIds};
            }
```

IMO this error appears maybe because I have disabled "Terms and Conditions".

Any solution?

**Comment by xnhinzkyx** [comment]
As I tried it, commenting those lines fixed the issue. I guess that is not the best solution to fix the issue but works fine for me.

**Comment by maxwhite** [comment]
Could you provide version of Magento please ?

**Comment by xnhinzkyx** [comment]
It's magento 2.1.7.

**Comment by maxwhite** [comment]
Couldn't reproduce the issue
