### ISSUE TITLE
Can't use refund online from back-office in Magento2

### ISSUE THREAD

**Issue by swieczkowski** [DIBS-Payment-Services/magento2-dibs-flexwin#24]
When we try to do a refund online in Magento 2.1.7 back-office.
Order > Invoice > Creditmemo > Refund

Error message was in reponse:
"Online refund was declined by DIBS<br>Error: <i>Sending MD5 is required</i>"

This md5key was missing in params Refund.php
source: http://tech.dibspayment.com/D2/API/Payment_functions/refundcgi

Fixed here: https://github.com/DIBS-Payment-Services/magento2-dibs-flexwin/pull/23

**Comment by maxwhite** [comment]
Fixed: 4995c2657a1f4bec3673e7a16e549f8254d5ad25
