### ISSUE TITLE
Credit memo results in a 502 error

### ISSUE THREAD

**Issue by oefterdal** [DIBS-Payment-Services/magento2-dibs-flexwin#27]
If I do a refund I get a 502, but it does get refunded on Dibs side, but we don't get the right feedback in Magento. If I try again I get refund declined, so there I get the correct feedback.

**Comment by oefterdal** [comment]
I haven't found a workaround.

**Comment by maxwhite** [comment]
Could you provide Magento version and your environment configuration ?

**Comment by oefterdal** [comment]
We are running nginx, and using Magento ver. 2.1.9

**Comment by oefterdal** [comment]
@maxwhite Do you have any info?

**Comment by maxwhite** [comment]
HI,
could you check if setting Create invoice is enabled in your Magento backend ?
If yes, try to disable it temporary. 
We are working on the issue. It will be fixed asap
