### ISSUE TITLE
DIBS module conflicting with Order comment extension

### ISSUE THREAD

**Issue by Fredrik-H-Laastad** [DIBS-Payment-Services/magento2-dibs-flexwin#28]
Hi Maksim, please see issue descrition provided by develeoper below, is this something that will be changed in future updates?

About the Order comment field, we have used multiple different solutions to add Order comment on Checkout page, which are mentioned here: 
CustomerParadigm Order comment: 
https://www.customerparadigm.com/magento-2-order-comments-extension-for-checkout/ 
This solution will appear after payment method steps, and it's not have save order comment button, but while this allows to pass attached order comment when order placed, but this is again not allowing to redirect to DIBS payment window after clicking Order Place button. -, 
We have confirmed that, this order comment working for other 3rd party payment redirection option while its not working only with DIBS. 
Boldcommerce Order comment: 
https://github.com/boldcommerce/magento2-ordercomments 
This solution will appear with each payment option under payment method step, and again it's not have save order comment button, order comment pass when order placed, but this is again not allowing to redirect to DIBS payment window after clicking Order Place button.

---

We are assuming the issue here is, DIBS payment using common method for saving order details same as Order comment module and magento before passing to Dibs window, clear the cart and save the Order comment and Order also placed - but it just not redirecting to Dibs window correctly. 
we have enabled the solution on test site lys.webexpressen.no.

![](https://dibs.zendesk.com/attachments/token/HnjOk8QwrN4youofQJuAL3CKP/?name=kommentar+felt+i+checkout+konflikt+med+DIBS.png)

**Comment by unicoder88** [comment]
Hi @Fredrik-H-Laastad , it looks like you've bumped into exactly same situation I had earlier https://github.com/DIBS-Payment-Services/magento2-dibs-flexwin/pull/16

At the moment we wound up using forked Dibs version with checkout JS models refactored code, but I'll try to rework it in a way working in Magento 2.0+ so that it might make it to upstream.
