### ISSUE TITLE
PHP 7.1 and Magento 2.2 support

### ISSUE THREAD

**Issue by mattias** [DIBS-Payment-Services/magento2-dibs-flexwin#30]
Currently when doing `composer require dibs/module-payment-flexwin` we get:
>  [InvalidArgumentException]                                                                            
>   Could not find package dibs/module-payment-flexwin at any version matching your PHP version 7.1.10.0

**Comment by mattias** [comment]
I just noticed this was closed but the only change is to allow php 7.1.
However, the code is not compatible with php 7.1 as is.

For example, "Void" is now a reserved keyword in php 7.1 which means some classes needs to be renamed, code using these classes needs to be updated and xml files needs to be updated to reflect the new changes.

**Comment by maxwhite** [comment]
I agree, thanks I'll fix this
