### ISSUE TITLE
Capture API not using storeview config

### ISSUE THREAD

**Issue by Fredrik-H-Laastad** [DIBS-Payment-Services/magento2-dibs-flexwin#33]
Hello!

A merchant has a issue where their shop is configured with 3 different countries spread across three different Merchant IDs. 

This works fine on the front-end and new payments are going towards their respective countries, however all attempts at capture seem to go towards the same merchant ID. Thus 2/3 of the captures fail with error "Wrong merchant".

Please look into how the capture function can be used on a multifront site.

**Comment by zohaibmir** [comment]
I can confirm this issue. we are also getting the same problem for one of our client.

**Comment by maxwhite** [comment]
Hi, try to check this release: 
https://github.com/DIBS-Payment-Services/magento2-dibs-flexwin/releases/tag/2.3.7
support for different store view has been added
