### ISSUE TITLE
Can't Checkout because of formKeyValidator

### ISSUE THREAD

**Issue by abad93** [DIBS-Payment-Services/magento2-dibs-flexwin#36]
If you try to checkout using guest checkout and login using the registered email, then select Dibs as payment, and then click the Place Order Button, you will get javascript error and can't checkout.

<img width="869" alt="console error message" src="https://user-images.githubusercontent.com/20398332/54006812-df14e100-4199-11e9-823b-1cf934e50325.png">

This is because of this $this->formKeyValidator->validate($this->_request) in /vendor/dibs/module-payment-flexwin/Controller/Index/Request.php. Dibs form key is different from magento form key.

Can someone fix it?

To fix it for now, I removed this $this->formKeyValidator->validate($this->_request). But it is not the right way to fix it.

**Comment by meandor-ua** [comment]
Hi, you could apply the patch, which works just fine for Magento 2.
Removing of the security feature is not an option.

`--- Controller/Index.orig.php	2019-04-09 15:58:38.000000000 +0300
+++ Controller/Index.php	2019-04-09 23:23:15.000000000 +0300
@@ -2,7 +2,11 @@
 
 namespace Dibs\Flexwin\Controller;
 
-abstract class Index extends \Magento\Framework\App\Action\Action
+use Magento\Framework\App\CsrfAwareActionInterface;
+use Magento\Framework\App\RequestInterface;
+use Magento\Framework\App\Request\InvalidRequestException;
+
+abstract class Index extends \Magento\Framework\App\Action\Action implements CsrfAwareActionInterface
 {
     protected $order;
     protected $quote;
@@ -28,4 +32,20 @@
     {
        return $this->getRequest()->getParam(\Dibs\Flexwin\Model\Method::KEY_ORDERID_NAME) ? true : false;
     }
+
+    /**
+     * {@inheritDoc}
+     */
+    public function createCsrfValidationException(RequestInterface $request): ?InvalidRequestException
+    {
+        return null;
+    }
+
+    /**
+     * {@inheritDoc}
+     */
+    public function validateForCsrf(RequestInterface $request): ?bool
+    {
+        return true;
+    }
 }
\ No newline at end of file
`
[dibs_callback_accept_post_request_fix.patch.txt](https://github.com/DIBS-Payment-Services/magento2-dibs-flexwin/files/3090191/dibs_callback_accept_post_request_fix.patch.txt)

It would be difficult just to include this patch to the repo as it brings backward incompatibility. This is Magento 2.3 issue. Magento core team introduced new security features, which made some modules backward incompatible with 2.3.0 and higher.
